linters:
  enable-all: true
  disable:
    - exhaustruct # Disallows to left unused fields in structs
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - ireturn # Disallows to return Interfaces
    - gci # Disable gci import ordering checker since its buggy
    - forcetypeassert # Disallows to use type assertions without checking
    - depguard # Disallows to use non-listed packages
    - gochecknoglobals # We like global variables
    - tagalign # Buggy
    - err113 # We like to use dynamic errors
    - musttag # Buggy
linters-settings:
  gosec:
    excludes:
      - 'G601'
  cyclop:
    max-complexity: 12
run:
  go: '1.24'
  timeout: 10m
  tests: false
