version: "2"
run:
  go: "1.25"
  tests: false
linters:
  default: all
  disable:
    - exhaustruct
    - wrapcheck
    - gochecknoinits
    - ireturn
    - forcetypeassert
    - depguard
    - gochecknoglobals
    - tagalign
    - fatcontext
    - revive
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 12
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports