watchers:
  - source:
      apiVersion: "apps/v1"
      kind: "Deployment"
    destination:
      method: "POST"
      urlTemplate: "YOUR_SLACK_WEBHOOK_URL"
      bodyTemplate: |
        {
          "text": "{{ .metadata.name }}"
        }
