watchers:
  - source:
      apiVersion: "apps/v1"
      kind: "Deployment"
    destination:
      method: "POST"
      urlTemplate: "https://webhook.site/c9181128-0355-430c-9d14-907a2c493b02"
      bodyTemplate: |
        {
          "text": "{{ .metadata.name }}"
        }
