taps:
  - name: MyDeployments
    kind: Deployment
    apiVersion: apps/v1
sinks:
  - name: MySlackWebhook
    method: POST
    urlTemplate: "YOUR_API_ENDPOINT"
    bodyTemplate: "{\"text\":\"Name: {{ .metadata.name }}\nAvailableReplicas: {{ .status.availableReplicas }}\"}"
flows:
  - tap: MyDeployments
    sink: MySlackWebhook
