apiVersion: cloud.spaceship.com/v1alpha2
kind: Watcher
metadata:
  name: example-rewritten
  namespace: default
spec:
  source:
    apiVersion: "apps/v1"
    kind: "Deployment"
    concurrency: 5
    lifecyclePolicies: [ "useFinalizer" ]
  filter:
    create: "object.metadata.name.contains('example')"
    update: "oldObject.metadata.generation != object.metadata.generation"
    delete: "true"
  destination:
    http:
      urlTemplate: "https://webhook-site.namecheapcloud.wtf/52bd8955-d0a5-4ef8-b23b-fc07f0324393"
      bodyTemplate: |
        {
          "name": "{{ .object.metadata.name }}",
          "namespace": "{{ .object.metadata.namespace }}",
          "replicas": {{ .object.spec.replicas | default 0 }}
        }
      headerTemplate: "\"Content-Type\": \"application/json\""
