apiVersion: cloud.spaceship.com/v1alpha2
kind: Watcher
metadata:
  name: example
  namespace: default
spec:
  source:
    apiVersion: "apps/v1"
    kind: "Deployment"
    concurrency: 5
    lifecyclePolicies: [ "useFinalizer" ]
  filter:
    create: "(timestamp(now) - timestamp(object.metadata.creationTimestamp) < duration('24h')) && object.metadata.name.contains('example')"
  destination:
    http:
      urlTemplate: "https://webhook-site.namecheapcloud.wtf/d429a92c-6590-4dc4-affa-b1293fa79b25"
      bodyTemplate: "{{ toPrettyJSON .object }}"
      headerTemplate: "\"Content-Type\": \"application/json\""
