apiVersion: cloud.spaceship.com/v1alpha2
kind: Watcher
metadata:
  name: simple-watcher-2
  namespace: default
spec:
  source:
    apiVersion: "v1"
    kind: "Pod"
  destination:
    method: "POST"
    urlTemplate: "https://webhook.site/37358195-fc85-474e-a22c-a4eb7ae5cc4f"
    bodyTemplate: | 
      {{ "simple-watcher-2 }}
