apiVersion: cloud.spaceship.com/v1alpha1
kind: Watcher
metadata:
  name: website-1
  namespace: default
spec:
  source:
    apiVersion: "apps/v1"
    kind: "Deployment"
  destination:
    method: "POST"
    urlTemplate: "YOUR_ENDPOINT_URL"
    bodyTemplate: |
      {
        "text": "{{ .metadata.name }}"
      }
