apiVersion: cloud.spaceship.com/v1alpha1
kind: Watcher
metadata:
  name: website-1
  namespace: default
spec:
  source:
    apiVersion: "apps/v1"
    kind: "Deployment"
  filter:
    object:
      namespace: "default"
  destination:
    method: "POST"
    urlTemplate: ""
    bodyTemplate: |
      {
        "text": "{{ .metadata.name }}"
      }
  valuesFrom:
    secretRef:
      name: "asd"
      namesace: "sdfd"
      key: "ggg"