name: Test
on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.21"
  GOPRIVATE: "github:com/NCCloud/*"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        run: |
          ./devops.sh generate
          git diff --exit-code
      - name: Coverage Report
        uses: gwatts/go-coverage-action@v1
        with:
          coverage-threshold: 0
          cover-pkg: ./...
          ignore-pattern: |
            .*cmd.*
            .*mocks.*
            .*apis.*
            .*generated.*
