name: Test
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write

env:
  GO_VERSION: "1.21"
  GOPRIVATE: "github:com/NCCloud/*"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        run: |
          ./devops.sh generate
          git diff --exit-code
      - name: Test Preparation
        run: |
          ./devops.sh prepare_envtest
      - run: "go test -v -covermode=count -coverprofile=coverage.out"
      - uses: jandelgado/gcov2lcov-action@v1
      - uses: kcjpop/coverage-comments@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: './coverage/clover.xml'
