name: Test
on:
  pull_request:
  push:
    branches:
      - main
permissions: write-all

env:
  GO_VERSION: "1.21"
  GOPRIVATE: "github:com/NCCloud/*"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        run: |
          ./devops.sh generate
          git diff --exit-code
      - name: Test Preparation
        run: |
          ./devops.sh prepare_envtest
      - name: Test
        run: |
          ./devops.sh test
      - uses: jandelgado/gcov2lcov-action@v1
        with:
          outfile: lcov.info
      - uses: hrishikesh-kadam/setup-lcov@v1
      - uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          minimum-coverage: 80
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
